# Generated by Django 5.2.4 on 2025-07-13 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='purpose',
            field=models.CharField(choices=[('register', 'Register'), ('reset', 'Reset Password')], default='register', max_length=16),
        ),
    ]
